# Generated by Django 3.1.3 on 2020-11-03 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commits',
            name='message',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='commits',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='repository',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
