# Generated by Django 3.1.3 on 2020-11-10 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_auto_20201104_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commits',
            name='message',
            field=models.TextField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='commits',
            name='timestamp',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='commits',
            name='title',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
    ]
